settings:
  RivalOne:
    port: 50001
    host: sim-api.rivalsystems.cloud
  SRE:
    url_base: https://srm-api.sterlingtradingtech.com/pts-risk
  ActivOnePlatform:
    host: 127.0.0.1
  ActivContentPlatform:
    host: 192.168.1.36:9010
    table: 602
    output_fields: 456;280;362;329
  General:
    start_time: "09:00:00"
    end_time: "17:00:00"
    run_days: "Mon-Fri"
credentials:
  RivalOne:
    username: kkibbe
    password: "thou-wordplay-iberian"
    group: KKIBBE
  SRE:
    username: VelFalconAPI
    password: VelFalAP1!
    account: VCPS-655-675557-P
  ActivOnePlatform:
    username: replay
    password: replay
  ActivContentPlatform:
    username: replay
    password: replay